### ISSUE TITLE
why do you use Kafka

### ISSUE THREAD

**Issue by HoangNgo88** [mmackowiak98/kafka-springboot-library#1]
Hi, I am reading your project and I love this project
I have a question, why do you choose Kafka in your project instead of others like RabbitMQ or ZeroMQ, are there any special feature but others dont have it. Can you share me about it. I am wondering when I should choose Kafka instead of others like RabbitMQ or ZeroMQ

**Comment by mmackowiak98** [comment]
Kafka seems to handle big data better that RabbitMQ for example. Another pros that stands behind Kafka is that it's more widely use and for me the overall architecture and working with Kafka is easier and more enjoyable. Of course there might be some cases where it's better to use something else than Kafka, maybe RabbitMQ for complex routing or even client requirements, but if there is no specific requirement my choice falls on Kafka
